root = "../"
luaservice = root.."Lua_service/?.lua;"..root.."test/?.lua;"..root.."examples/?.lua;"..root.."test/?/init.lua"
lualoader = root .. "Lua_base/loader.lua"
lua_path = root.."Lua_base/?.lua;"..root.."Lua_base/?/init.lua"
--lua_cpath = root .. "../Bin/?.dll"
lua_cpath = root .. "Bin/?.so"
snax = root.."examples/?.lua;"..root.."test/?.lua"
